//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class information
	{
		string title;
		string mouseOverText;
		string description;
		public information (string title, string mouseOverText, string description)
		{
			this.title = title;
			this.mouseOverText = mouseOverText;
			this.description = description;
		}
	}
}

